### ISSUE TITLE
Upgrade MongoDB Dependency to Version 5.0 or Higher

### ISSUE THREAD

**Issue by ShunPin** [SAMA-Communications/sama-server#105]
Our project currently uses MongoDB version 4.4. We need to upgrade the MongoDB dependency to version 5.0 or higher. This upgrade is necessary to take advantage of the new features, improvements, and security enhancements available in the latest versions.

**Comment by IgorKhomenko** [comment]
@ShunPin thanks for reporting it. I have added a ticket to our TODO list.

Meanwhile, I assume that can be easily done since we do not use any exotic MongoDB API, 
so probably you could try it on your end by changing the following and let us know:
- update npm package version here https://github.com/SAMA-Communications/sama-server/blob/main/package.json#L32
- update docker compose https://github.com/SAMA-Communications/sama-server/blob/main/docker-compose.yml#L115

**Comment by ShunPin** [comment]
I haven't modified any code yet; I only changed the connection information for mongoDB to an internal development environment using mongodb:7.0.11, and it is currently working fine.
If I encounter any issues later, I will modify and test it, then provide feedback.

**Comment by IgorKhomenko** [comment]
I believe this can be closed
