### ISSUE TITLE
Offline messaging and history

### ISSUE THREAD

**Issue by afilp** [SAMA-Communications/sama-server#74]
Hello!

Do you support offline messaging / history, i.e. the other user is offline when I sent a message but then gets online and receives all unreceived messages, etc.

In that respect, do you have a DB schema for this purpose?

Thanks!

**Comment by Oleksandr1414** [comment]
@afilp Hi, thank you for your question 💭

We didn't implement this feature because it can cause problems with a large number of requests when authorizing a user.

As an alternative solution to this issue, we have provided the following case:
- when a user logs in for the first time, we synchronize chats  and the counter of unread messages (use [conversation_list](https://github.com/SAMA-Communications/sama-server/blob/main/docs/API.md#list-conversations));
- when opening a chat with new messages, we use [message_list](https://github.com/SAMA-Communications/sama-server/blob/main/docs/API.md#list-messages) to get the latest messages (or all of them).
  
You can see 👀 these and other implementations in our client repository [sama-client](https://github.com/SAMA-Communications/sama-client), which may also help answer your questions. 
  
If you still have questions, I will be glad to answer them 🙌🏻
